const tuple = <T extends string[]>(...args: T) => args;
const animateName = tuple(
  // ----- 进入 -----
  // '淡入',
  'fadeIn',
  // '向下淡入',
  'fadeInDown',
  // '大幅向下淡入',
  'fadeInDownBig',
  // '向左淡入',
  'fadeInLeft',
  // '大幅向左淡入',
  'fadeInLeftBig',
  // '向右淡入',
  'fadeInRight',
  // '大幅向右淡入',
  'fadeInRightBig',
  // '向上淡入',
  'fadeInUp',
  // '大幅向上淡入',
  'fadeInUpBig',
  // '向左移入',
  'slideInLeft',
  // '向右移入',
  'slideInRight',
  // '向下移入',
  'slideInDown',
  // '弹入',
  'bounceIn',
  // '向左弹入',
  'bounceInLeft',
  // '向右弹入',
  'bounceInRight',
  // '向上弹入',
  'bounceInUp',
  // '向下弹入',
  'bounceInDown',
  // 'X轴翻转进入',
  'flipInX',
  // 'Y轴翻转进入',
  'flipInY',
  // '光速进入',
  'lightSpeedIn',
  // '旋转进入',
  'rotateIn',
  // '左下旋转进入',
  'rotateInDownLeft',
  // '右下旋转进入',
  'rotateInDownRight',
  // '左上旋转进入',
  'rotateInUpLeft',
  // '右上旋转进入',
  'rotateInUpRight',
  // '从左滚入',
  'rollIn',
  // ----- 强调 -----
  // '弹跳',
  'bounce',
  // '闪烁',
  'flash',
  // '放大缩小',
  'pulse',
  // '抖动',
  'rubberBand',
  // '左右晃动',
  'shake',
  // '悬摆',
  'swing',
  // '放大抖动',
  'tada',
  // '左右悬摆',
  'wobble',
  // '翻转',
  'flip',
  // ----- 退出 -----
  // '淡出',
  'fadeOut',
  // '向下淡出',
  'fadeOutDown',
  // '大幅向下淡出',
  'fadeOutDownBig',
  // '向左淡出',
  'fadeOutLeft',
  // '大幅向左淡出',
  'fadeOutLeftBig',
  // '向右淡出',
  'fadeOutRight',
  // '大幅向右淡出',
  'fadeOutRightBig',
  // '向下淡出',
  'fadeOutUp',
  // '大幅向下淡出',
  'fadeOutUpBig',
  // '向左移出',
  'slideOutLeft',
  // '向右移出',
  'slideOutRight',
  // '向上移出',
  'slideOutUp',
  // '向下移出',
  'slideOutDown',
  // '弹出',
  'bounceOut',
  // '向下弹出',
  'bounceOutDown',
  // '向左弹出',
  'bounceOutLeft',
  // '向右弹出',
  'bounceOutRight',
  // '向上弹出',
  'bounceOutUp',
  // 'X轴翻转移出',
  'flipOutX',
  // 'Y轴翻转移出',
  'flipOutY',
  // '光速移出',
  'lightSpeedOut',
  // '旋转移出',
  'rotateOut',
  // '左下旋转移出',
  'rotateOutDownLeft',
  // '右下旋转移出',
  'rotateOutDownRight',
  // '左上旋转移出',
  'rotateOutUpLeft',
  // '右上旋转移出',
  'rotateOutUpRight',
  // '向左脱落',
  'hinge',
  // '向右滚出',
  'rollOut',
);
export default animateName;
